spring:
  main:
    sources: br.com.cielo.pfi.web

logging:
  level:
    ROOT: ${LOG_LEVEL:ERROR}
    br.com.cielo.pfi.web: ERROR

msg:
  trans:
    not:
      found: Nenhuma transa\u00e7\u00e3o foi encontrada para os crit\u00e9rios informados [cod. erro \#C11].
  erro:
    excesso:
      registros: O Relat\u00f3rio excedeu o n\u00famero m\u00e1ximo de 5 mil registros, necess\u00e1rio diminuir o per\u00edodo da consulta.


spring:
  profiles:
    active: ${SPRING_PROFILE:prod}
  application:
    name: pfi-web

cors:
  url: ${CORS_URL:https://qasnews.cielo.com.br, localhost}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
  port: ${SERVER_PORT:8081}

proxy:
  host: ${PROXY_HOST:proxytrnhml.enterprisetrn.hdevelo.com.br}
  port: ${PROXY_PORT:8080}

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    info:
      enabled: true
    health:
      show-details: always
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:info,health,loggers,httptrace,metrics,mappings}
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

feign:
  client:
    config:
      auth-service:
        url: ${FEIGN_CLIENT_AUTH_SRV_URL:http://auth-service:8080}
      local-services:
        url: ${FEIGN_CLIENT_LOCAL_SRV_URL:http://localhost:8083}
      user-management:
        url: ${FEIGN_CLIENT_USER_MANAGEMENT_URL:http://localhost:8082}
      default:
        connectTimeout: 160000000
        readTimeout: 160000000